Agregar el nuevo plan
comcomUBA/dcubabot pull request #66
Opened 2022-12-14 17:43 UTC by GalileoCap

Actualiza el comando `/flan` para que devuelva el plan nuevo, y agrega el comando `/flanv` para el flan viejo.
Idealmente recibiría el parámetro `/flan v` para el viejo, en lugar de que sea otro comando. Pero no supe hacerlo así.

Lo testeé yo a mano no sé si hay un proceso de testeo. Pero lo dejo corriendo así que pueden hablarle acá: https://t.me/GaliBot_test_bot

2022-12-14 18:47 UTC, GalileoCap commented
Corregí el link al bot, estaba uno viejo

2022-12-16 03:29 UTC, franciscod commented
lgtm

2022-12-16 12:20 UTC, rozen03 requested changes
Para mi le falta algo intuitivo, para que la gente no se quede como "uh no se como ver el viejo"
le agregaria un mensaje que diga "para ver el mensaje viejo manda /flanv".

Junto a eso, en el codigo agregaria un comment q diga "deprecame despues del DD/MM/YYYY" o algo asi

2022-12-16 13:04 UTC, GalileoCap commented
> le agregaria un mensaje que diga "para ver el mensaje viejo manda /flanv".
No veo en el código cómo poner texto junto a la imágen. Podría cambiarlo para que se pueda, o que mande un mensaje de texto más (aunque creo que ningún otro comando manda más de un mensaje). ¿Qué te parece mejor?

> agregaria un comment q diga "deprecame despues del DD/MM/YYYY" o algo asi
El plan viejo sigue por cinco años más así que se iría para el primer cuatri 2028, ¿no? ¿Le pongo después de la cursada de verano y antes de las inscripciones?

2023-03-26 03:35 UTC, closed without merging