Cast error code to str
comcomUBA/dcubabot pull request #69
Opened 2023-05-02 15:07 UTC by CamiKaseM7

Cuando el campus esta caido y cae en el `HTTPError` el `status_code` es un int, cuando intentas concatenarlo con el mensaje te da el error: 

```
msg = "Recibí una respuesta del campus con error. " + response.status_code + ": " + response.reason
TypeError: can only concatenate str (not "int") to str
``` 

Solo hay que castearlo a str para que funcione.

2023-05-02 15:31 UTC, rozen03 requested changes

2023-05-02 16:28 UTC, CamiKaseM7 commented on campus.py
> +        msg = "Recibí una respuesta del campus con error. " + str(response.status_code) + ": " + response.reason
Te convence asi? 
```py
f"Recibí una respuesta del campus con error. {response.status_code}: {response.reason}"
```

2023-05-02 17:08 UTC, rozen03 commented on campus.py
> +        msg = "Recibí una respuesta del campus con error. " + str(response.status_code) + ": " + response.reason
perfecto

2023-05-02 17:10 UTC, rozen03 commented
Cuando pueda mergearlo, lo apruebo.

Cualquier cosa pingueame si cuelgo.

2023-05-04 23:34 UTC, CamiKaseM7 commented
Friendly reminder @rozen03

2023-05-05 21:53 UTC, rozen03 approved these changes

2023-05-05 21:53 UTC, merged