Enviar mensaje cuando hay concierto en River
comcomUBA/dcubabot pull request #72
Opened 2023-11-11 07:24 UTC by crivasr

La verdad es que no me gustó hacerlo asi. Si cambian los tags en algun momento hay que cambiarlo todo para scrapear y hay que hacer malabares con los locales para parsear la fecha. 

Encontré despues esto https://serpapi.com/google-events-api supuestamente te da 100 requests gratis por mes, se podria crear una cuenta ahi para sacar los datos

2023-11-13 17:40 UTC, crivasr commented
@rozen03

2023-11-13 18:02 UTC, rozen03 requested changes

2023-11-13 18:02 UTC, rozen03 commented on river.py
> +        if "vs" in titulo.lower():
Por otro lado, me gusto como atacaste esto, probaste que onda si los partidos en river estan todos?

2023-11-13 18:02 UTC, rozen03 commented on river.py
> +        if "vs" in titulo.lower():
De todas formas hay un problema con este filtro, si algun evento tiene "vs" como parte del nombre, lo va a ignorar, supongo q si separas por espacios te quedaria algo mejor filtrable

2023-11-13 18:05 UTC, franciscod commented on river.py
> +    browser.open(f"https://www.google.com/search?q={query}&ibp=htl;events")
hay altas[1] chances de que esto deje de funcionar despues de un par de corridas desde la ip de bot

1: (citation needed)

2023-11-13 18:09 UTC, franciscod commented
encontré una alternativa para buscar los proximos conciertos, no se que tan fiable será: https://www.songkick.com/es/venues/4514007-estadio-river-plate

2023-11-13 18:12 UTC, franciscod commented
otra fuente posible: https://indiehoy.com/eventos/

2023-11-13 19:07 UTC, crivasr commented on river.py
> +        if "vs" in titulo.lower():
Solo queda un partido en river este año, por lo menos ese está. No sabria decirte el resto. 

Si buscas por "partidos en river" te sale el de argentina uruguay que en realidad se cambió a la bombonera. Y el concierto de taylor que se pasó al domingo, nunca apareció. Parece no ser muy sensible a cambios de ultimo momento.

2023-11-13 19:07 UTC, crivasr commented on river.py
> +    browser.open(f"https://www.google.com/search?q={query}&ibp=htl;events")
aunque sea solo una vez por dia? donde esta hosteado el bot? es verdad que si la ip es de algun host conocido, aws/ovh/google/etc lo pueden filtrar facilmente

2023-11-13 19:07 UTC, crivasr commented
> encontré una alternativa para buscar los proximos conciertos, no se que tan fiable será: https://www.songkick.com/es/venues/4514007-estadio-river-plate
> 
> (tienen una api que sale $500 USD/mes)

Parece mas facil de scrapear esa, nos ahorramos la suscripcion jajasj

2023-11-13 19:16 UTC, rozen03 commented on river.py
> +    browser.open(f"https://www.google.com/search?q={query}&ibp=htl;events")
yo creo q hasta finde año no tenemos problema por eso igual, si surgen problemas, nos vamos a enterar en verano y podemos ver q onda

2023-11-14 16:02 UTC, franciscod commented
capaz se puede usar alguna api de google? si la data de ellos es buena tal vez sea buena idea

(idea de Rozen)

2023-11-14 17:49 UTC, crivasr commented
No hay una api de ellos todavia, hay un [issue](https://serpapi.com/search.json?engine=google_events&q=Events+in+Austin) del 2019 donde lo piden

2023-11-14 18:38 UTC, crivasr commented
Por si crapeamos de alguna de las 2 que mandaste @franciscod se puede hacer con esto 

```py
print("indiehoy: ")
browser.open("https://indiehoy.com/eventos/")

for el in browser.select(".list-style-event"):
    lugar = el.select(".location")[0].text
    fecha = el.select(".dtstart")[0].text
    titulo = el.select(".summary")[0].text
    
    if "River" not in lugar:
        continue
    print(lugar, fecha, titulo)
    
print("")
print("songkick: ")
browser.open("https://www.songkick.com/venues/4514007-estadio-river-plate/calendar")

for el in browser.select(".microformat"):
    info = json.loads(el.select("script")[0].text)[0]
    lugar = info["location"]["name"]
    fecha = info["startDate"]
    titulo = info["name"] # = info.performer[0].name
        
    print(lugar, fecha, titulo)
```

me dio esto:

```
indiehoy: 
Estadio River Plate 21/11/2023 Roger Waters en Argentina
Estadio River Plate 22/11/2023 Roger Waters en Argentina
Estadio River Plate 24/11/2023 Red Hot Chili Peppers en Argentina

songkick: 
Estadio River Plate 2023-11-21 Roger Waters
Estadio River Plate 2023-11-22 Roger Waters
Estadio River Plate 2023-11-24 Red Hot Chili Peppers
Estadio River Plate 2023-11-24T18:00:00-0300 Irontom
Estadio River Plate 2023-11-26 Red Hot Chili Peppers
Estadio River Plate 2023-11-26T18:00:00-0300 Irontom
Estadio River Plate 2023-12-08T20:00:00-0300 Tan Bionica
Estadio River Plate 2024-03-23T20:00:00-0300 Maria Becerra
```

2023-11-14 18:48 UTC, rozen03 commented
Convengamos q si hay un recital en river songkick lo va a tener, se dedican a eso y river no es el teatro flores (?)

2023-11-14 18:49 UTC, rozen03 commented
Si te da mucha duda y tenes ganas de ser hyper preciso, dado q son cosas  bastante planeadas, se pueden hacer varias consultas a lugares distintos y compaginar

2023-11-14 20:46 UTC, crivasr commented
Nah, creo que con songkick es suficiente. No los conocia pero parece bien cuidada la pagina

2023-11-17 15:20 UTC, rozen03 commented
LGTM

2023-11-17 15:21 UTC, rozen03 approved these changes

2023-11-17 15:22 UTC, rozen03 commented
@franciscod ya q estas investido en esto miratelo vos tambien antes de q lo mergee.

2023-11-20 12:33 UTC, franciscod commented
mergealo noma

2023-11-21 11:50 UTC, merged